name: poke_repository
description: My new Flutter package
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  poke_api:
    path: "../poke_api"
  json_annotation: ^4.6.0
  equatable: ^2.0.5
  mocktail: ^0.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
  json_serializable: ^6.3.1
  build_runner: ^2.0.0